Added flag to remove duplicated images and update database
sivaschenko/magento2-clean-media pull request #9
Opened 2020-10-08 17:44 UTC by peterjaap

2020-10-08 17:45 UTC, peterjaap commented
This PR also includes the changes in #7 and #8

2020-10-08 18:59 UTC, peterjaap commented
My local test;

```
8228 duplicated files have been deleted
0 rows have been updated in the catalog_product_entity_varchar table
26333 rows have been updated in the catalog_product_entity_media_gallery table
764 Mb has been freed.
```

2020-10-12 13:00 UTC, sivaschenko requested changes
Thanks for all the contributions @peterjaap ! Please see my improvement suggestions.

2020-10-12 13:00 UTC, sivaschenko commented on Service/DuplicateFileFinder.php
> +class DuplicateFileFinder {
Can you please format the code o match Magento standards and be consistent for better readability

(probably I have to add some kind of static tests to the repo for objectivity))

2020-10-12 13:00 UTC, sivaschenko commented on Command/CatalogMedia.php
> +        if ($input->getOption(self::INPUT_KEY_LIST_DUPES)) {
The method becomes too long. I'd extract this complex part of logic to a separate class

2021-03-09 14:05 UTC, peterjaap commented
@sivaschenko could you take a look at this PR again please?

2021-04-19 10:55 UTC, sivaschenko commented
Refactored the implementation and introduced a separate command for duplicates.
Need to test the PR and update README before merging

2021-04-28 09:23 UTC, peterjaap commented
@sivaschenko nice, LGTM! :+1:

2021-06-06 20:10 UTC, merged